"""
CORTEX — Houdini JSON → TypeScript Converter
==============================================
Run this from your terminal (NOT inside Houdini):
    python houdini_to_ts.py

Prerequisites:
    - houdini_nodes_export.json must exist on your Desktop
      (generated by houdini_export.py run inside Houdini)
    - houdini-nodes.ts must exist at the path below

What it does:
    1. Reads houdini_nodes_export.json
    2. Converts every node to a HoudiniNodeDef object
    3. Deduplicates against nodes already in houdini-nodes.ts
    4. Appends new nodes before the final `]` in houdini-nodes.ts
"""

import json
import os
import re
import sys

# ── Paths — edit if yours differ ──────────────────────────────────────────────
JSON_INPUT  = os.path.join(os.path.expanduser("~"), "Desktop", "houdini_nodes_export.json")
TS_FILE     = r"D:\FRIXXY\APP\cortex\src\data\houdini-nodes.ts"

# ── Category → object-type map ────────────────────────────────────────────────
CATEGORY_TYPE = {
    "sop":     "software_node",
    "vop":     "material_node",
    "dop":     "simulation_node",
    "chop":    "channel_node",
    "lop":     "scene_node",
    "top":     "task_node",
    "cop":     "compositing_node",
    "rop":     "output_node",
    "object":  "object_node",
    "shop":    "shader_node",
    "vex":     "vex_node",
    "manager": "manager_node",
    "director":"director_node",
}

# ── Namespace → vendor tags ───────────────────────────────────────────────────
NAMESPACE_TAGS = {
    "labs":      ["sidefx_labs", "labs"],
    "redshift":  ["redshift", "maxon", "renderer"],
    "arnold":    ["arnold", "autodesk", "renderer"],
    "vray":      ["vray", "chaos", "renderer"],
    "karma":     ["karma", "sidefx", "renderer"],
    "kinefx":    ["kinefx", "animation", "rigging"],
    "apex":      ["apex", "procedural_rigging"],
}

def clean_name(raw: str) -> str:
    """Strip namespace/version qualifiers for a clean short name."""
    # e.g.  "labs::breaker::2.0"  →  "labs_breaker"
    parts = raw.replace("::", "_").split("_")
    # drop version-like segments  (digits or  \d+\.\d+)
    cleaned = [p for p in parts if not re.fullmatch(r"[\d.]+", p)]
    return "_".join(cleaned)


def node_to_ts_obj(node: dict) -> dict | None:
    """Convert a raw JSON node dict to a HoudiniNodeDef-compatible dict."""
    raw_name  = node.get("name", "").strip()
    if not raw_name:
        return None

    category  = node.get("category", "sop").lower()
    namespace = node.get("namespace", "").lower()
    display   = node.get("displayName") or raw_name.replace("_", " ").title()

    # Build tags
    base_tags = ["houdini", category]
    if namespace and namespace not in base_tags:
        base_tags.append(namespace)
    extra = NAMESPACE_TAGS.get(namespace, [])
    for t in extra:
        if t not in base_tags:
            base_tags.append(t)
    # Merge tags from Houdini itself (short strings only)
    for t in node.get("tags", []):
        ts = str(t).lower().replace(" ", "_")
        if ts and ts not in base_tags:
            base_tags.append(ts)

    # Inputs list
    in_labels  = node.get("inputLabels",  [])
    max_in     = node.get("maxInputs", 0)
    out_labels = node.get("outputLabels", [])
    max_out    = node.get("maxOutputs", 1)

    def make_connectors(labels, count, prefix):
        result = []
        n = max(len(labels), min(count, 8))   # cap at 8 to avoid huge lists
        for i in range(n):
            label = labels[i] if i < len(labels) else f"{prefix}{i+1}"
            result.append({"id": f"{prefix}{i+1}", "label": str(label)})
        return result

    inputs  = make_connectors(in_labels,  max_in,  "in")
    outputs = make_connectors(out_labels, max_out, "out")

    # Parameters — convert to our schema
    parms_out = []
    for p in node.get("parameters", [])[:40]:   # cap at 40 per node
        pname = p.get("name", "")
        if not pname or pname.startswith("__"):
            continue
        po = {
            "name":  pname,
            "label": p.get("label", pname),
            "type":  p.get("type", "float"),
        }
        if "default" in p:
            po["default"] = p["default"]
        if "min" in p:
            po["min"] = p["min"]
        if "max" in p:
            po["max"] = p["max"]
        if "menuItems" in p:
            po["options"] = [m["value"] for m in p["menuItems"][:12]]
        parms_out.append(po)

    return {
        "name":        clean_name(raw_name),
        "displayName": display,
        "category":    category,
        "objectType":  CATEGORY_TYPE.get(category, "software_node"),
        "description": f"{display} node ({category.upper()}).",
        "tags":        base_tags[:12],
        "inputs":      inputs,
        "outputs":     outputs,
        "parameters":  parms_out,
    }


def ts_value(v, indent=0) -> str:
    pad = "  " * indent
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        escaped = v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        if not v:
            return "[]"
        if all(isinstance(i, str) for i in v):
            inner = ", ".join(ts_value(i) for i in v)
            return f"[{inner}]"
        # multi-line for lists of objects
        lines = [f"{pad}  " + ts_value(i, indent + 1) for i in v]
        return "[\n" + ",\n".join(lines) + f"\n{pad}]"
    if isinstance(v, dict):
        lines = []
        for k, val in v.items():
            lines.append(f'{pad}  "{k}": {ts_value(val, indent + 1)}')
        return "{\n" + ",\n".join(lines) + f"\n{pad}}}"
    return f'"{v}"'


def node_to_ts_string(node: dict) -> str:
    lines = ["  {"]
    for k, v in node.items():
        lines.append(f'    "{k}": {ts_value(v, 2)},')
    lines.append("  }")
    return "\n".join(lines)


def get_existing_names(ts_path: str) -> set[str]:
    """Return set of node 'name' values already in the TS file."""
    names = set()
    with open(ts_path, encoding="utf-8") as f:
        content = f.read()
    for m in re.finditer(r'"name"\s*:\s*"([^"]+)"', content):
        names.add(m.group(1))
    return names


def append_nodes_to_ts(new_nodes: list[dict], ts_path: str):
    with open(ts_path, encoding="utf-8") as f:
        content = f.read()

    # Find the last `}` before the closing `]`
    last_brace = content.rfind("}")
    if last_brace == -1:
        print("ERROR: Could not find closing } in TS file.")
        sys.exit(1)

    ts_blocks = [node_to_ts_string(n) for n in new_nodes]
    insertion = ",\n" + ",\n".join(ts_blocks)

    new_content = content[:last_brace + 1] + insertion + content[last_brace + 1:]

    with open(ts_path, "w", encoding="utf-8") as f:
        f.write(new_content)

    print(f"✓ Appended {len(new_nodes)} nodes to {ts_path}")


def main():
    # ── 1. Load JSON ────────────────────────────────────────────────────────
    if not os.path.exists(JSON_INPUT):
        print(f"ERROR: Cannot find {JSON_INPUT}")
        print("Run houdini_export.py inside Houdini first.")
        sys.exit(1)

    with open(JSON_INPUT, encoding="utf-8") as f:
        raw_nodes = json.load(f)
    print(f"Loaded {len(raw_nodes)} nodes from JSON.")

    # ── 2. Get existing names ───────────────────────────────────────────────
    existing = get_existing_names(TS_FILE)
    print(f"Existing nodes in TS file: {len(existing)}")

    # ── 3. Convert + deduplicate ────────────────────────────────────────────
    converted = []
    skipped   = 0
    seen      = set(existing)

    for raw in raw_nodes:
        node = node_to_ts_obj(raw)
        if node is None:
            skipped += 1
            continue
        if node["name"] in seen:
            skipped += 1
            continue
        seen.add(node["name"])
        converted.append(node)

    print(f"New nodes to add : {len(converted)}")
    print(f"Skipped (dup/bad): {skipped}")

    if not converted:
        print("Nothing to add — already up to date.")
        return

    # ── 4. Append to TS ─────────────────────────────────────────────────────
    append_nodes_to_ts(converted, TS_FILE)

    # ── 5. Print summary ────────────────────────────────────────────────────
    from collections import Counter
    cats = Counter(n["category"] for n in converted)
    print("\nBreakdown by category:")
    for cat, count in sorted(cats.items(), key=lambda x: -x[1]):
        print(f"  {cat:<12} +{count}")


if __name__ == "__main__":
    main()
