import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))
const root  = join(__dir, '..')

const src = readFileSync(join(root, 'src/data/houdini-nodes.ts'), 'utf8')
const match = src.match(/export const HOUDINI_NODES = (\[[\s\S]*\])\s*$/)
if (!match) { console.error('Could not find HOUDINI_NODES array'); process.exit(1) }

const nodes = (new Function('return ' + match[1]))()
console.log(`Parsed ${nodes.length} nodes`)

function esc(s) {
  if (s == null) return 'NULL'
  return `'${String(s).replace(/'/g, "''")}'`
}
function escJson(v) {
  if (!v || (Array.isArray(v) && v.length === 0)) return `'[]'`
  return esc(JSON.stringify(v))
}

const now = new Date().toISOString()
const lines = [
  '-- Auto-generated by scripts/generate-seed.mjs — DO NOT EDIT',
  `-- Generated: ${now} — ${nodes.length} nodes`,
  '',
  'BEGIN;',
]

for (const n of nodes) {
  const id = crypto.randomUUID()
  lines.push(
    `INSERT OR IGNORE INTO nodes ` +
    `(id, vault_id, software_id, name, display_name, category, object_type, ` +
    `description, version, color, icon, tags, inputs, outputs, parameters, ` +
    `documentation, notes, production_tips, media_ids, is_deprecated, metadata, created_at, updated_at) VALUES (` +
    `${esc(id)},NULL,NULL,` +
    `${esc(n.name)},${esc(n.displayName)},` +
    `${esc(JSON.stringify(n.category))},${esc(JSON.stringify(n.objectType))},` +
    `${esc(n.description)},${esc(n.version ?? null)},${esc(n.color ?? null)},${esc(n.icon ?? null)},` +
    `${escJson(n.tags)},${escJson(n.inputs)},${escJson(n.outputs)},${escJson(n.parameters)},` +
    `${esc(n.documentation ?? null)},${esc(n.notes ?? null)},${escJson(n.productionTips)},` +
    `'[]',0,'{}',${esc(now)},${esc(now)}` +
    `);`
  )
}

lines.push('COMMIT;')

const outDir = join(root, 'src-tauri/src/data')
mkdirSync(outDir, { recursive: true })
const outPath = join(outDir, 'nodes_seed.sql')
writeFileSync(outPath, lines.join('\n'))
console.log(`✓ Written → ${outPath}`)
console.log(`  File size: ${(lines.join('\n').length / 1024 / 1024).toFixed(1)} MB`)
